src-git packages https://github.com/openwrt/packages.git;lede-17.01
src-git luci https://github.com/openwrt/luci.git;lede-17.01
src-git routing https://github.com/openwrt-routing/packages.git;lede-17.01
src-git telephony https://github.com/openwrt/telephony.gi;lede-17.01
src-git onion https://github.com/OnionIoT/OpenWRT-Packages.git;lede-17.01
src-git oboo https://github.com/ouellettetech/Oboo-Packages.git
