name: Build Firmware

on:
  push:
    branches:
      - main
      - fixbuild
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ca-certificates \
            curl \
            unzip \
            nodejs \
            npm \
            python3
          echo "Checking Certs..."
          git config --list | grep ssl  || true
          echo "Running Update Ca Cert."
          sudo update-ca-certificates
          echo "Updating Certs..."
          git config --list | grep ssl  || true
          echo "After Checking Certs..."

      - name: Fix shell + permissions
        run: |
          chmod +x build.sh

      - name: Build firmware
        run: |
          bash ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-build
          path: |
            output/**
            build/**
            dist/**
